### PR TITLE
Replace git protocol with http in dependencies

### PR DESCRIPTION
**Pull request by PascalLeMerrer**
Fixes issue #13

### CODE REVIEW

**Comment by austinkelleher** [comment]
Hey, @PascalLeMerrer. Thanks for the PR. I think this is more of an issue with your corporate proxy. Many node modules use this same pattern, so I think you will continue to run into this issue. After a quick Google search, I think you can set a git config option that will tell git to use the `https` protocol instead of `git`. Does this work for you?

`git config --global url."https://".insteadOf git://`

Reference: https://stackoverflow.com/questions/14937405/npm-git-protocol-dependencies

**Comment by austinkelleher** [comment]
Also, npm 5 writes the url as the following when running `npm install mlrawlings/marko-magic`:

`"marko-magic": "github:mlrawlings/marko-magic"`

Does that work for you?

**Comment by PascalLeMerrerPro** [comment]
Thanks for your answers, Austin

The proxy does not support the git protocol and there is no way for me to change that (it should change before the end of the year, but I can't wait for that).

Modifying the git config works for the installation, although it has a drawback: I assume all of my git requests will use https instead of git protocol, including the requests to our internal git servers. I could live with that, but it's definitely not optimal.

However, this does not solve everything. After installing marko-cli and marko-starter with the modified git config, executing `marko create hello-world` results in:

```
✖ Unable to find a matching app template. None of the following exist:
  - marko-js-samples/demo
  - marko-js-samples/marko-demo
  - marko-js-samples/marko-starter-demo
```

Doing the same thing with a direct Internet connection works well.
Do you know why?

**Comment by austinkelleher** [comment]
I apologize for the late response on this. I just published `marko-starter@1.2.1` with a version of `marko-magic` that is published to npm. This issue should be resolve. As a side note, `marko-starter@2` does not require `marko-magic` at all.

**Pull request closed without merging**
